name: test push2 filters
on:
  push:
    branches: [main]
    paths:
      - 'src/**'
concurrency: 
  group: one_at_a_time
  cancel-in-progress: true
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "this is the push2"
